spring:
  datasource:
    hikari:
#      jdbc-url: jdbc:h2:./test
      username: sa
      password: password
      driver-class-name: org.h2.Driver
      jdbc-url: "jdbc:h2:mem:db"
    embedded-database-connection: h2
  main:
    allow-bean-definition-overriding: true

  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    user:
      name: user
      password: password
  jpa:
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: always
